services:
  - type: web
    name: lima-fashion-backend
    env: python
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "gunicorn --chdir backend app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SUPER_ADMIN_USERNAME
        value: superadmin
      - key: SUPER_ADMIN_PASSWORD
        sync: false
